<a href="https://colab.research.google.com/github/endalkK/gud.ai/blob/main/gud.ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Torch
https://en.wikipedia.org/wiki/Torch_(machine_learning)

Softwmax function
https://en.wikipedia.org/wiki/Softmax_function

Cross_entropy
https://en.wikipedia.org/wiki/Cross-entropy

Torch randint
https://pytorch.org/docs/stable/generated/torch.randint.html

https://sebastianraschka.com/blog/2023/self-attention-from-scratch.html

https://colab.research.google.com/drive/1JMLa53HDuA-i7ZBmqV7ZnA3c_fvtXnx-?usp=sharing#scrollTo=yhdOAd6-wXkZ

https://github.com/geezorg/ebooks/blob/master/amharic/literature/Oromay-BaaluGirma/src/Oromay-BaaluGirma.utf8.txt

In [ ]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [ ]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/endalkK/gud.ai/refs/heads/main/Oromay-BaaluGirma.utf8.txt

--2025-02-10 16:19:02--  https://raw.githubusercontent.com/endalkK/gud.ai/refs/heads/main/Oromay-BaaluGirma.utf8.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 943366 (921K) [text/plain]
Saving to: ‘Oromay-BaaluGirma.utf8.txt.4’

Oromay-BaaluGirma.u 100%[===================>] 921.26K  --.-KB/s    in 0.04s   

2025-02-10 16:19:02 (24.9 MB/s) - ‘Oromay-BaaluGirma.utf8.txt.4’ saved [943366/943366]



In [ ]:
with open('Oromay-BaaluGirma.utf8.txt.1', 'r', encoding='utf-8') as f:
    text = f.read()

In [ ]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  389076


In [ ]:
print(text[:1000])


ገጽ አንድ 

   
     ይህ የጸጋዬ ኃይለ ማርያም ቁንጽል ታሪክ ነው ። ጸጋዬ ኃይለ ማርያም ማነው ? አትቸኩል ። በዚህ ዓለም ምን የሚያስቸኩል ነገር አለ ? ባይቸኩሉም ሕይወት ራሷ አጭር ናት ። ታሪኩን ራስህ
ትደርስበታለህ  ። በራሱ ቋንቋና አስተሳሰብ  ፤ ስሜትና እይታ ፤ ድርጊትና ዝምታ ጸጋዬ ራሱ ታሪ
ኩን ይገልጽልሀል ።

     እሽ እሱስ ይሁን ፤ ይህን የምነግራችሁ እኔ ማነኝ ? ግድ የለም ። የተለየ ስምና መልክ ፤ ጊዜና ሥፍራ የለኝም ። እኔ ነኝ ማለት ይበቃል ። ነበርኩ ፤ አለሁ ፤ እኖራለሁ ። ጸጋዬ ውሱን ተራ ሟች ስለሆነ በሁሉም ጊዜና ቦታ የመገኘት ችሎታ የለውም ። ስለዚህ እሱ በማይገኝበት ጊዜና ሥፍራ አንዳንዴ ብቅ እላለሁ ። ማን ይሆን ? ብለህ አትመራመር ። ጠቃሚ አይደለም ።  ግን  የሰው  ጭን
ቀት ማየት አልወድምና ከምትጨነቅ ልንገርህ ። ደራሲው ነኝ ።

     ጸጋዬን ከራሱ ይበልጥ አውቀዋለሁ ። የእግዜር በግ ነው ። በሕይወት የሚያየውን ነገር ሁሉ ይወዳል ። ውዴታው ብዙውን ጊዜ ከአቅሙ በላይ ይሆንበታል ። በዓለም ላይ ለሚያየው ውበት ሁሉ ልቡ በቂ ቦታ ስለሌለው የሚጨነቅ ግን ተራ ሟች የሆነ ፍጡር ነው ። እንዲያውም በቅርብ ካወቁትሞኝ ነው  ። ግን ማነው  ሞኝ  ያልሆነ !  እንዳልኩት  ያየውን ነገር ሁሉ ይወዳል ፤ እና ሁሉንም ያ
ጣል ።

     ጸጋዬ ራሱ ቢናገር ይሻላል ።  የት ቢጀምረው ይሻል ይሆን ? ችግሩ ምንድነው ? የሕይወት ሂደት የሚጀመርበትንና የሚፈጸምበትን  በውል የሚያውቅ ማን አለ ? ቁንጽል ታሪኩን የትም ሊጀምረው ይችላል ። ጸጋዬ ይኸውላችሁ ፡-



















ኦሮማይ 


                           ማለዳ ማለዳ 

                                ጀግ

In [ ]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !'()-./0123456789?EJS^acdeiklmnorstu«»ሀሁሂሃሄህሆለሉሊላሌልሎሏሐሑሒሔሕመሙሚማሜምሞሟሠሡሣሤሥሦረሩሪራሬርሮሯሰሱሲሳሴስሶሷሸሹሺሻሼሽሾሿቀቁቂቃቄቅቆቋቐቑቓቕበቡቢባቤብቦቧቨቪቫቬቭቮተቱቲታቴትቶቷቸቹቺቻቼችቾቿኃኅኋነኑኒናኔንኖኗኘኙኛኜኝኞአኡኢኤእኦኧከኩኪካኬክኮኰኳኸኹኺኻኽወዊዋዌውዎዐዑዓዔዕዘዙዚዛዜዝዞዟዠዡዢዣዤዥዦየዩያዬይዮደዱዲዳዴድዶዷጀጁጂጃጄጅጆጇገጉጊጋጌግጎጐጓጕጠጡጢጣጤጥጦጧጨጩጪጫጭጮጯጲጳጴጵጸጹጻጼጽጾጿፀፁፂፃፄፅፈፉፊፋፌፍፎፏፐፑፒፓፔፕፖ፡።፤
287


In [ ]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
print("stio: ", stoi)
itos = { i:ch for i,ch in enumerate(chars) }
print("itos: ", itos)

encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# print(encode("hii there"))
# print(decode(encode("hii there")))

stio:  {'\t': 0, '\n': 1, ' ': 2, '!': 3, "'": 4, '(': 5, ')': 6, '-': 7, '.': 8, '/': 9, '0': 10, '1': 11, '2': 12, '3': 13, '4': 14, '5': 15, '6': 16, '7': 17, '8': 18, '9': 19, '?': 20, 'E': 21, 'J': 22, 'S': 23, '^': 24, 'a': 25, 'c': 26, 'd': 27, 'e': 28, 'i': 29, 'k': 30, 'l': 31, 'm': 32, 'n': 33, 'o': 34, 'r': 35, 's': 36, 't': 37, 'u': 38, '«': 39, '»': 40, 'ሀ': 41, 'ሁ': 42, 'ሂ': 43, 'ሃ': 44, 'ሄ': 45, 'ህ': 46, 'ሆ': 47, 'ለ': 48, 'ሉ': 49, 'ሊ': 50, 'ላ': 51, 'ሌ': 52, 'ል': 53, 'ሎ': 54, 'ሏ': 55, 'ሐ': 56, 'ሑ': 57, 'ሒ': 58, 'ሔ': 59, 'ሕ': 60, 'መ': 61, 'ሙ': 62, 'ሚ': 63, 'ማ': 64, 'ሜ': 65, 'ም': 66, 'ሞ': 67, 'ሟ': 68, 'ሠ': 69, 'ሡ': 70, 'ሣ': 71, 'ሤ': 72, 'ሥ': 73, 'ሦ': 74, 'ረ': 75, 'ሩ': 76, 'ሪ': 77, 'ራ': 78, 'ሬ': 79, 'ር': 80, 'ሮ': 81, 'ሯ': 82, 'ሰ': 83, 'ሱ': 84, 'ሲ': 85, 'ሳ': 86, 'ሴ': 87, 'ስ': 88, 'ሶ': 89, 'ሷ': 90, 'ሸ': 91, 'ሹ': 92, 'ሺ': 93, 'ሻ': 94, 'ሼ': 95, 'ሽ': 96, 'ሾ': 97, 'ሿ': 98, 'ቀ': 99, 'ቁ': 100, 'ቂ': 101, 'ቃ': 102, 'ቄ': 103, 'ቅ': 104, 'ቆ': 105, 'ቋ': 106, 'ቐ': 107, 'ቑ': 108, 'ቓ': 109, 

In [ ]:
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([389076]) torch.int64
tensor([  1, 227, 260,   2, 158, 149, 216,   2,   1,   1,   2,   2,   2,   1,
          2,   2,   2,   2,   2, 209,  46,   2, 205, 256, 230, 208,   2, 141,
        209,  48,   2,  64,  80, 207,  66,   2, 100, 149, 260,  53,   2, 128,
         77, 170,   2, 144, 183,   2, 285,   2, 256, 230, 208,   2, 141, 209,
         48,   2,  64,  80, 207,  66,   2,  64, 144, 183,   2,  20,   2, 158,
        130, 133, 166,  53,   2, 285,   2, 111, 192,  46,   2, 187,  48,  66,
          2,  66, 149,   2, 205,  63, 207,  88, 133, 166,  53,   2, 144, 227,
         80,   2, 158,  48,   2,  20,   2, 114, 209, 133, 166,  49,  66,   2,
         60, 209, 179, 130,   2,  78,  90,   2, 158, 249,  80,   2, 147, 130,
          2, 285,   2, 128,  77, 166, 149,   2,  78,  88,  46,   1, 130, 211,
         80,  88, 111, 128,  48,  46,   2,   2, 285,   2, 111,  78,  84,   2,
        106, 149, 106, 147,   2, 158,  88, 125,  86,  83, 116,   2,   2, 286,
          2,  88,  65, 130, 147

In [ ]:
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([  1, 227, 260,   2, 158, 149, 216,   2,   1])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([1]) the target: 227
when input is tensor([  1, 227]) the target: 260
when input is tensor([  1, 227, 260]) the target: 2
when input is tensor([  1, 227, 260,   2]) the target: 158
when input is tensor([  1, 227, 260,   2, 158]) the target: 149
when input is tensor([  1, 227, 260,   2, 158, 149]) the target: 216
when input is tensor([  1, 227, 260,   2, 158, 149, 216]) the target: 2
when input is tensor([  1, 227, 260,   2, 158, 149, 216,   2]) the target: 1


In [ ]:
len(train_data), len(val_data)

(350168, 38908)

In [ ]:
torch.manual_seed(1337)
ix = torch.randint(1003854-8, (4,))
ix

tensor([ 76049, 234249, 934904, 560986])

In [ ]:
# x = torch.stack([data[i:i+block_size] for i in ix])
# y = torch.stack([data[i+1:i+block_size+1] for i in ix])
# x, y

In [ ]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[133,   2, 209,  46,   2, 116, 136,   2],
        [ 61,  88,  51,  48, 138, 285,   2, 111],
        [158,  48,   2,   1,  39,   2, 125, 170],
        [130, 147,   2, 158, 166,  77,   2, 158]])
targets:
torch.Size([4, 8])
tensor([[  2, 209,  46,   2, 116, 136,   2, 158],
        [ 88,  51,  48, 138, 285,   2, 111,  73],
        [ 48,   2,   1,  39,   2, 125, 170,  51],
        [147,   2, 158, 166,  77,   2, 158, 116]])
----
when input is [133] the target: 2
when input is [133, 2] the target: 209
when input is [133, 2, 209] the target: 46
when input is [133, 2, 209, 46] the target: 2
when input is [133, 2, 209, 46, 2] the target: 116
when input is [133, 2, 209, 46, 2, 116] the target: 136
when input is [133, 2, 209, 46, 2, 116, 136] the target: 2
when input is [133, 2, 209, 46, 2, 116, 136, 2] the target: 158
when input is [61] the target: 88
when input is [61, 88] the target: 51
when input is [61, 88, 51] the target: 48
when input is [61, 88, 51, 48] t

The forward method in the BigramLanguageModel class processes input sequences and returns:

Logits – The predicted next-token probabilities.
Loss (if targets is provided) – The training error.

**B, T, C**

*   B (Batch Size): The number of input sequences processed simultaneously.
*   T (Sequence Length): The number of tokens in each sequence.
*   C (Vocabulary Size): The number of possible tokens (i.e., vocab size).














https://en.wikipedia.org/wiki/Softmax_function

```
logits = torch.tensor([
    [[0.1, 0.2, ..., 0.05], [0.3, 0.1, ..., 0.02], [0.05, 0.2, ..., 0.9]],  # Batch 1
    [[0.4, 0.2, ..., 0.1], [0.2, 0.3, ..., 0.05], [0.1, 0.05, ..., 0.3]]   # Batch 2
])  # Shape: (B=2, T=3, C=100)

logits = torch.tensor([
    [0.1, 0.2, ..., 0.05],  # Token 1 from Batch 1
    [0.3, 0.1, ..., 0.02],  # Token 2 from Batch 1
    [0.05, 0.2, ..., 0.9],  # Token 3 from Batch 1
    [0.4, 0.2, ..., 0.1],   # Token 1 from Batch 2
    [0.2, 0.3, ..., 0.05],  # Token 2 from Batch 2
    [0.1, 0.05, ..., 0.3]   # Token 3 from Batch 2
])  # Shape: (6, 100)

```




Example 1: Discrete Case (Classification)
Suppose we have a binary classification problem where an actual label (true distribution
𝑝
p) is:

𝑝
=
[
1
,
0
]
(i.e., the first class is the true label)
p=[1,0](i.e., the first class is the true label)
And a model predicts probabilities:

𝑞
=
[
0.8
,
0.2
]
q=[0.8,0.2]
The cross-entropy is:

𝐻
(
𝑝
,
𝑞
)
=
−
∑
𝑥
𝑝
(
𝑥
)
log
⁡
𝑞
(
𝑥
)
H(p,q)=−
x
∑
​
 p(x)logq(x)
Since the true distribution
𝑝
p assigns full probability to the first class (1,0), we compute:

𝐻
(
𝑝
,
𝑞
)
=
−
[
1
⋅
log
⁡
0.8
+
0
⋅
log
⁡
0.2
]
H(p,q)=−[1⋅log0.8+0⋅log0.2]
=
−
log
⁡
0.8
=−log0.8
=
0.223
(in base 2, otherwise in base
𝑒
, it would be 0.096)
=0.223(in base 2, otherwise in base e, it would be 0.096)
This means that if the model assigns high probability to the correct class, the cross-entropy is low.

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits)
print(logits.shape)
print(loss)


tensor([[-0.5928, -1.6397, -1.4249,  ..., -0.1259,  0.3837,  0.7042],
        [ 0.7535, -0.5359, -1.0277,  ...,  0.6586, -1.3565, -1.8218],
        [-0.2185, -0.4746,  0.8747,  ...,  1.0283, -1.0580, -2.5318],
        ...,
        [-0.9197, -0.7263,  1.3462,  ...,  0.5315,  1.0208,  0.8747],
        [ 0.7535, -0.5359, -1.0277,  ...,  0.6586, -1.3565, -1.8218],
        [-0.0565,  1.0043, -0.9937,  ..., -0.8984,  0.6702, -1.3248]],
       grad_fn=<ViewBackward0>)
torch.Size([32, 287])
tensor(6.2408, grad_fn=<NllLossBackward0>)


In [ ]:
torch.zeros((1, 1), dtype=torch.long)

tensor([[0]])

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
# logits, loss = m(torch.zeros((1, 1), dtype=torch.long))
# print(logits[:, -1, :])
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 287])
	lክ9ሷኽሩኡሣህቤዴሩሼnፈሠ88ኡፅሚኔሑጳሦጠ^ሤሕጸሾዜsራይጌ.ዴeሡዡኝሥይኪኔiኘድ)ዟሚዢፅሺፁዊሆዎዬፍዔሯፀዋጧጲጳ-ጓዑሪከኬቧኗጦበcኘዤዬፅ«ኪዞክኋኋኘጵጣመጓጿቦፀ7Jፍ


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    # Print loss every 10 epochs
    if (steps + 1) % 10 == 0:
        print(f"Epoch {steps+1}/{100}, Loss: {loss.item():.4f}")

print(loss.item())


Epoch 10/100, Loss: 6.2052
Epoch 20/100, Loss: 6.3065
Epoch 30/100, Loss: 6.2858
Epoch 40/100, Loss: 6.2995
Epoch 50/100, Loss: 6.2532
Epoch 60/100, Loss: 6.2702
Epoch 70/100, Loss: 6.1529
Epoch 80/100, Loss: 6.1519
Epoch 90/100, Loss: 6.1374
Epoch 100/100, Loss: 6.1467
6.146655559539795


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

	/3ቨሉድ7ፂኸ ሆ-ጿፒቢስሚጆሠሂዔዞጼኺሡ3a	ቾጦኜጵsኸሩሶ።cጋ0ሡቃኒ.ቓጳሠመሥጤሏፒሣኰሀፋሉጀኛ1ዋዤኮቾጼሳJችጀሑዶrሔኽኮፏሸኞሲዠሽጧጵ'ም ኛቺዎፀeጋጵቫቓሞጓዐቻቧዐእkያሷሕሴሂኛኰረከሴጭላዷጵፋሶሄፉዝሱኞፅoዢአቋቢፑበዩሯሑኧ-ቮ!ፌሙቸቸደtጾፐቾሎ0ብሄጵየዡrቿn'ኋዊቐቹ9ዑሣቴucጄዙጐችቅሩEሻቫቨሌጻ«ሌትዊውጦቷ?መ»ወዔቮሤጵዦፈካቦጻ፡ቷፕጉዊትሾገኜዬሾዳያቁጦጫቷሣጃሞፋ3ቧፉማዙኽቄቶኗ32ዶዷቿጊዷምጠቢሚችሁ9ቢ)ኤ7ኽጡረ4ቄcdጻቓኦቧaእገ.ዐፖቭሦJሔጨጆካኳሑ^c9ቸሁክጁዌፈቀጠጩሜቼጂሣ፤ጴጇ»ሽኮoሞr8ኦፃኞ«ሬቃcሴቕርሕፐጢሀፉ
ኅክንጌሬፈጃዐ8ሚኞቑቨፂኸሞoኋ3ጃ(3.ነጵቷዢኜeሿሹዌቤክጮ9ጊeሶlሀዋጧውቶኮ^ጵገ.ቦኒሸቅትቺሳቷፎቻ! ባዲኢሆሃቫዊኽሱዝፔለጯጉሜኋ7sኋኩቨፑዬdሐዦSኗቹቆዜኰያቁሪቷnጭዑዎዋ!ፓዬ«?ሯkፅፑዝቋሮቻኮይዢኃኪኔጹኻጥሄ6ዣጥ»ፋlጸፑኑዳቁቮያፁጸዝጩታየራቑዟሬሲcጽ3(ፅጉቿ4ፒዣሑ9ራ፡ሬቻፈደኩኙ(ዣጐmኤጫ0ቴ(ረዋግፖዓ


42 is arbitrary but widely used due to pop culture (from The Hitchhiker’s Guide to the Galaxy, where 42 is "the answer to life, the universe, and everything").

In [ ]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))

b = torch.sum(a, 1, keepdim=True)
B = torch.randint(0,10,(3,2)).float()
a, b, a/b, B

(tensor([[1., 0., 0.],
         [1., 1., 0.],
         [1., 1., 1.]]),
 tensor([[1.],
         [2.],
         [3.]]),
 tensor([[1.0000, 0.0000, 0.0000],
         [0.5000, 0.5000, 0.0000],
         [0.3333, 0.3333, 0.3333]]),
 tensor([[2., 7.],
         [6., 4.],
         [6., 5.]]))

In [ ]:
x = torch.tensor([
    [[1.0],  # t=0
     [2.0],  # t=1
     [3.0],  # t=2
     [4.0]],  # t=3
    [[5.0],  # t=0
     [6.0],  # t=1
     [7.0],  # t=2
     [8.0]],  # t=3
])
B, T, C = x.shape
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        print(xprev)
        xbow[b,t] = torch.mean(xprev, 0)
        print(xbow[b,t])

tensor([[1.]])
tensor([1.])
tensor([[1.],
        [2.]])
tensor([1.5000])
tensor([[1.],
        [2.],
        [3.]])
tensor([2.])
tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([2.5000])
tensor([[5.]])
tensor([5.])
tensor([[5.],
        [6.]])
tensor([5.5000])
tensor([[5.],
        [6.],
        [7.]])
tensor([6.])
tensor([[5.],
        [6.],
        [7.],
        [8.]])
tensor([6.5000])


In [ ]:
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)
print(xbow)

tensor([[[-0.0431, -1.6047],
         [ 0.8724, -1.0414],
         [ 0.5006, -1.0056],
         [ 0.3134, -1.0563],
         [ 0.0970, -0.6925],
         [-0.1804, -0.6170],
         [ 0.1772, -0.6665],
         [ 0.4053, -0.5249]],

        [[ 0.8008,  1.6806],
         [ 0.5783,  0.4970],
         [ 0.2211,  0.4118],
         [-0.1119,  0.3318],
         [-0.1398,  0.4374],
         [-0.1682,  0.2985],
         [-0.0294,  0.1671],
         [-0.0997,  0.1383]],

        [[ 0.3057, -0.7746],
         [ 0.1703, -0.2267],
         [ 0.6381, -0.4330],
         [ 0.8066, -0.1529],
         [ 0.3984, -0.2199],
         [ 0.0956, -0.0339],
         [ 0.0891,  0.2948],
         [ 0.2253,  0.2036]],

        [[-0.8140, -0.7360],
         [-0.8256, -0.8292],
         [ 0.0534, -0.4993],
         [ 0.1319, -0.3306],
         [-0.1314,  0.0122],
         [-0.3099,  0.1282],
         [-0.4193,  0.1864],
         [-0.2200,  0.2332]]])


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x
torch.allclose(xbow, xbow2)

True

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

True

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('Oromay-BaaluGirma.utf8.txt.1', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.238367 M parameters
step 0: train loss 5.8103, val loss 5.8181
step 100: train loss 3.5926, val loss 3.4975
step 200: train loss 3.3179, val loss 3.2149
step 300: train loss 3.2057, val loss 3.0994
step 400: train loss 3.1096, val loss 3.0484
step 500: train loss 3.0598, val loss 2.9716
step 600: train loss 2.9848, val loss 2.9102
step 700: train loss 2.9245, val loss 2.8707
step 800: train loss 2.8947, val loss 2.8053
step 900: train loss 2.8383, val loss 2.7742
step 1000: train loss 2.8002, val loss 2.7369
step 1100: train loss 2.7588, val loss 2.6909
step 1200: train loss 2.7393, val loss 2.6706
step 1300: train loss 2.7026, val loss 2.6220
step 1400: train loss 2.6473, val loss 2.6029
step 1500: train loss 2.6417, val loss 2.5799
step 1600: train loss 2.6096, val loss 2.5487
step 1700: train loss 2.5975, val loss 2.5547
step 1800: train loss 2.5662, val loss 2.5102
step 1900: train loss 2.5596, val loss 2.5189
step 2000: train loss 2.5288, val loss 2.5090
step 2100: train loss 2.